services:

  mysql:
    container_name: morse-mysql
    build: ./morse-mysql/
    restart: always
    environment:
      - MYSQL_DATABASE=morse
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 4s
      retries: 20
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: morse-redis
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

  rust-api:
    container_name: morse-api
    build: ./morse-api/
    restart: always
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=morse-mysql
      - MYSQL_DATABASE=morse
      - MYSQL_USER
      - MYSQL_PASSWORD
      - REDIS_HOST=morse-redis
      - REDIS_PASSWORD
      - JWT_SECRET
      - JWT_EXP_HOURS
      - WEB_DOMAIN

  nginx-front:
    container_name: morse-web
    build: ./morse-web/
    restart: always
    ports:
      - "8080:80"
    depends_on:
      rust-api:
        condition: service_started
    environment:
      - API_HOST=morse-api
      - API_PORT=8080
      - WEB_DOMAIN
    volumes:
      - ./morse-web/src/:/var/www/html:ro

volumes:
  mysql-data: {}
  redis-data: {}
